name: Build Mod from Source

on:
  workflow_dispatch:
  push:
    branches:
      - fabric-26.3
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - minecraft: '26.1'
            task: build
            artifact: build/forgix
          - minecraft: '26.2'
            task: build
            artifact: build/forgix
          - minecraft: '26.3'
            task: :fabric:build
            artifact: fabric/build/libs
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: 25

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build (${{ matrix.minecraft }})
        run: ./gradlew clean ${{ matrix.task }} -Pminecraft=${{ matrix.minecraft }}

      - name: Upload Artifact (${{ matrix.minecraft }})
        uses: actions/upload-artifact@v7
        with:
          name: Villager-Pickup-Mod-${{ matrix.minecraft }}
          path: ${{ matrix.artifact }}
